version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emailclient
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DSN: postgres://user:password@db:5432/emailclient?sslmode=disable
      SMTPPORT: ${SMTPPORT}
      SMTPSENDER: ${SMTPSENDER}
      SMTPHOST: ${SMTPHOST}
      SMTPUSERNAME: ${SMTPUSERNAME}
      SMTPPASS: ${SMTPPASS}
      URL: ${URL}
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
